# Generated by Django 2.0.13 on 2019-04-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_user_agent",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Last time Used user agent"
            ),
        )
    ]
