# Generated by Django 2.0.13 on 2019-04-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safesecret',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
